let main_div = document.createElement("div");
main_div.setAttribute("class", "container form");
let form = document.createElement("form");
form.setAttribute("onsubmit", "something()");
let div1 = document.createElement("div");
div1.setAttribute("class", "row p-3");
let div11 = document.createElement("div");
div11.setAttribute("class", "col-4 offset-2");
let label11 = document.createElement("label");
label11.setAttribute("for", "fname");
label11.innerText = "First Name";
div11.append(label11);
let div12 = document.createElement("div");
div12.setAttribute("class", "col-4");
let input11 = document.createElement("input");
input11.setAttribute("type", "text");
input11.setAttribute("id", "fname");
input11.setAttribute("name", "First Name");
input11.setAttribute("required", "true");
div12.append(input11);
div1.append(div11, div12);
let div2 = document.createElement("div");
div2.setAttribute("class", "row p-3");
let div21 = document.createElement("div");
div21.setAttribute("class", "col-4 offset-2");
let label21 = document.createElement("label");
label21.setAttribute("for", "lname");
label21.innerText = "Last Name";
div21.append(label21);
let div22 = document.createElement("div");
div22.setAttribute("class", "col-4");
let input21 = document.createElement("input");
input21.setAttribute("type", "text");
input21.setAttribute("id", "lname");
input21.setAttribute("name", "Last Name");
input21.setAttribute("required", "true");
div22.append(input21);
div2.append(div21, div22);
let div3 = document.createElement("div");
div3.setAttribute("class", "row p-3");
let div31 = document.createElement("div");
div31.setAttribute("class", "col-4 offset-2");
let label31 = document.createElement("label");
label31.setAttribute("for", "address");
label31.innerText = "Address";
div31.append(label31);
let div32 = document.createElement("div");
div32.setAttribute("class", "col-4");
let input31 = document.createElement("input");
input31.setAttribute("type", "text");
input31.setAttribute("id", "address");
input31.setAttribute("name", "Address");
input31.setAttribute("required", "true");
div32.append(input31);
div3.append(div31, div32);
let div4 = document.createElement("div");
div4.setAttribute("class", "row p-3");
let div41 = document.createElement("div");
div41.setAttribute("class", "col-4 offset-2");
let label41 = document.createElement("label");
label41.setAttribute("for", "pincode");
label41.innerText = "Pincode";
div41.append(label41);
let div42 = document.createElement("div");
div42.setAttribute("class", "col-4");
let input41 = document.createElement("input");
input41.setAttribute("type", "number");
input41.setAttribute("id", "pincode");
input41.setAttribute("name", "Pincode");
input41.setAttribute("required", "true");
div42.append(input41);
div4.append(div41, div42);
let div5 = document.createElement("div");
div5.setAttribute("class", "row p-3");
let div51 = document.createElement("div");
div51.setAttribute("class", "col-4 offset-2");
let label51 = document.createElement("label");
label51.setAttribute("for", "gender");
label51.innerText = "Gender";
div51.append(label51);
let div52 = document.createElement("div");
div52.setAttribute("class", "col-4");
let select1 = document.createElement("select");
select1.setAttribute("name", "Gender");
select1.setAttribute("id", "gender");
select1.setAttribute("required", "true");
let option1 = document.createElement("option");
option1.setAttribute("value", "M");
option1.innerText = "Male";
let option2 = document.createElement("option");
option2.setAttribute("value", "F");
option2.innerText = "Female";
let option3 = document.createElement("option");
option3.setAttribute("value", "Other");
option3.innerText = "Other";
select1.append(option1, option2, option3);
div52.append(select1);
div5.append(div51, div52);
let div6 = document.createElement("div");
div6.setAttribute("class", "row p-3");
let div61 = document.createElement("div");
div61.setAttribute("class", "col-4 offset-2");
let label61 = document.createElement("label");
label61.setAttribute("for", "food");
label61.innerText = "Choice of Food";
div61.append(label61);
let div62 = document.createElement("div");
div62.setAttribute("class", "col-4");
let input61 = document.createElement("input");
input61.setAttribute("type", "checkbox");
input61.setAttribute("id", "it");
input61.setAttribute("class", "food");
input61.setAttribute("name", "food");
input61.setAttribute("value", "Italian");
let input62 = document.createElement("input");
input62.setAttribute("type", "checkbox");
input62.setAttribute("id", "ch");
input62.setAttribute("class", "food");
input62.setAttribute("name", "food");
input62.setAttribute("value", "Chinese");
let input63 = document.createElement("input");
input63.setAttribute("type", "checkbox");
input63.setAttribute("id", "in");
input63.setAttribute("class", "food");
input63.setAttribute("name", "food");
input63.setAttribute("value", "Indian");
let input64 = document.createElement("input");
input64.setAttribute("type", "checkbox");
input64.setAttribute("id", "co");
input64.setAttribute("class", "food");
input64.setAttribute("name", "food");
input64.setAttribute("value", "Continental");
let input65 = document.createElement("input");
input65.setAttribute("type", "checkbox");
input65.setAttribute("id", "me");
input65.setAttribute("class", "food");
input65.setAttribute("name", "food");
input65.setAttribute("value", "Mexican");
div62.append(
  input61,
  "Italian",
  input62,
  "Chinese",
  input63,
  "Indian",
  input64,
  "Continental",
  input65,
  "Mexican"
);
div6.append(div61, div62);
let div7 = document.createElement("div");
div7.setAttribute("class", "row p-3");
let div71 = document.createElement("div");
div71.setAttribute("class", "col-4 offset-2");
let label71 = document.createElement("label");
label71.setAttribute("for", "state");
label71.innerText = "State";
div71.append(label71);
let div72 = document.createElement("div");
div72.setAttribute("class", "col-4");
let input71 = document.createElement("input");
input71.setAttribute("type", "text");
input71.setAttribute("id", "state");
input71.setAttribute("name", "State");
input71.setAttribute("required", "true");
div72.append(input71);
div7.append(div71, div72);
let div8 = document.createElement("div");
div8.setAttribute("class", "row p-3");
let div81 = document.createElement("div");
div81.setAttribute("class", "col-4 offset-2");
let label81 = document.createElement("label");
label81.setAttribute("for", "country");
label81.innerText = "Country";
div81.append(label81);
let div82 = document.createElement("div");
div82.setAttribute("class", "col-4");
let input81 = document.createElement("input");
input81.setAttribute("type", "text");
input81.setAttribute("id", "country");
input81.setAttribute("name", "Country");
input81.setAttribute("required", "true");
div82.append(input81);
div8.append(div81, div82);
let div9 = document.createElement("div");
div9.setAttribute("class", "row p-3");
let div91 = document.createElement("div");
div91.setAttribute("class", "col-4 offset-4");
let input91 = document.createElement("input");
input91.setAttribute("type", "submit");
input91.setAttribute("class", "bg-primary");
div91.append(input91);
div9.append(div91);
form.append(div1, div2, div3, div4, div5, div6, div7, div8, div9);
let table = document.createElement("table");
let tr1 = document.createElement("tr");
let th1 = document.createElement("th");
let th2 = document.createElement("th");
th1.innerText = "Item";
th2.innerText = "Value";
tr1.append(th1, th2);
let tr2 = document.createElement("tr");
let td1 = document.createElement("td");
let td2 = document.createElement("td");
td1.innerText = "First Name";
td2.setAttribute("class", "tablefname");
tr2.append(td1, td2);
let tr3 = document.createElement("tr");
let td3 = document.createElement("td");
let td4 = document.createElement("td");
td3.innerText = "Last Name";
td4.setAttribute("class", "tablelname");
tr3.append(td3, td4);
let tr4 = document.createElement("tr");
let td5 = document.createElement("td");
let td6 = document.createElement("td");
td5.innerText = "Address";
td6.setAttribute("class", "tableaddress");
tr4.append(td5, td6);
let tr5 = document.createElement("tr");
let td7 = document.createElement("td");
let td8 = document.createElement("td");
td7.innerText = "Pincode";
td8.setAttribute("class", "tablepincode");
tr5.append(td7, td8);
let tr6 = document.createElement("tr");
let td9 = document.createElement("td");
let td10 = document.createElement("td");
td9.innerText = "Gender";
td10.setAttribute("class", "tablegender");
tr6.append(td9, td10);
let tr7 = document.createElement("tr");
let td11 = document.createElement("td");
let td12 = document.createElement("td");
td11.innerText = "Choice of Food";
td12.setAttribute("class", "tablefood");
tr7.append(td11, td12);
let tr8 = document.createElement("tr");
let td13 = document.createElement("td");
let td14 = document.createElement("td");
td13.innerText = "State";
td14.setAttribute("class", "tablestate");
tr8.append(td13, td14);
let tr9 = document.createElement("tr");
let td15 = document.createElement("td");
let td16 = document.createElement("td");
td15.innerText = "Country";
td16.setAttribute("class", "tablecountry");
tr9.append(td15, td16);
table.append(tr1, tr2, tr3, tr4, tr5, tr6, tr7, tr8, tr9);
main_div.append(form, table);
document.body.append(main_div);
